version: '3.5'

networks:
  monitoring-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.1.0/24

services:
  mysql-server:
    image: mariadb:10.5
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./zbx_vol/var/lib/mysql:/var/lib/mysql:rw
      - ./config/conf.d:/etc/mysql/conf.d
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 250M
          cpus: '0.1'
    env_file:
      - ./env/.env_mysql
    stop_grace_period: 1m
    networks:
      monitoring-net:

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.2-latest
    container_name: zabbix-server
    hostname: zabbix
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_vol/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_vol/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_vol/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_vol/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_vol/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_vol/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_vol/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.95'
        reservations:
          memory: 512M
          cpus: '0.5'
    env_file:
      - ./env/.env_mysql
    depends_on:
      - mysql-server
    networks:
      monitoring-net:

  zabbix-web-front:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_vol/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.95'
        reservations:
          memory: 512M
          cpus: '0.5'
    env_file:
      - ./env/.env_mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - mysql-server
    networks:
      monitoring-net:

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.2-latest
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_vol/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_vol/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_vol/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_vol/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    env_file:
      - ./env/.env_agent
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.95'
        reservations:
          memory: 512M
          cpus: "0.5"
    networks:
      monitoring-net:

